config/routes.rb
RottenMangos::Application.routes.draw do

  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  namespace :admin do
    resource :users
  end
  
  get '/session/chooseadmin', to: "sessions#chooseadmin"

  post '/session/setadmin', to: "sessions#setadmin"

  root to: 'movies#index'

end

app/models/movie.rb
class Movie < ActiveRecord::Base

  has_many :reviews

  validates :title, presence: true
  validates :director, presence: true
  validates :runtime_in_minutes, numericality: { only_integer: true }
  validates :description, presence: true
  validates :release_date, presence: true
  validate :release_date_is_in_future
  validate :poster_image_file_or_url

  scope :search, -> (title, director, runtime_min, runtime_max) { where("title like ?", "%#{title}%")
                      .where("director like ?", "%#{director}%")
                      .where("runtime_in_minutes < #{runtime_max} AND runtime_in_minutes > #{runtime_min}") 
                    }

  mount_uploader :poster_image, ImageUploader

  def review_average
    if reviews.size > 0
      reviews.sum(:rating_out_of_ten)/reviews.size
    end
  end

  protected

  def release_date_is_in_future
    if release_date.present?
      errors.add(:release_date, "should be in the future") if release_date < Date.today
    end
  end

  def poster_image_file_or_url
    if !poster_image && !url
      errors.add(:poster_image, "file or url is required")
    end
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie

  validates :user, presence: true
  validates :text, presence: true
  validates :rating_out_of_ten, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_or_equal_to: 10 }
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :reviews, dependent: :destroy

  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :password, length: { in: 6..20 }, on: :create

  def full_name
    "#{firstname} #{lastname}"
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

    # def new
    # end

    # def create
    # end

  def show
    if session[:admin]
      @users = User.all.page(params[:page]).per(10)
    else
      redirect_to movies_path, notice: "You must be logged in as Admin to access that page."
    end
  end

  def destroy
    @user = User.find(params[:id])
    UserMailer.delete_email(@user).deliver_now
    @user.destroy
    redirect_to admin_users_path
  end
end

      

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    min_runtime = 0
    max_runtime = 1000
    if params[:runtime_in_minutes]
      if params[:runtime_in_minutes] == ""
        value1 = min_runtime
        value2 = max_runtime
      elsif params[:runtime_in_minutes] == '<90'
        value1 = min
        value2 = 90
      elsif params[:runtime_in_minutes] == '90..120'
        value1 = 90
        value2 = 120
      else params[:runtime_in_minutes] == '>120'
        value1 = 120
        value2 = max
      end
    end
    if params[:submit]
      @movies = Movie.search(params[:title], params[:director], value1, value2)
    else
      @movies = Movie.all
    end

  end

  def show
      @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update_attributes(movie_params)
      redirect_to movies_path
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

#   <%= form_tag(movies_search_path) do %>
#   <%= label_tag(:title, "Title:") %>
#   <%= text_field_tag(:title) %>
#   <%= label_tag(:director, "Director:") %>
#   <%= text_field_tag(:director) %>
#   <%= label_tag(:duration, "Duration:") %>
#   <%= select_tag :duration, "<option value></option><option value='<90'>Less than 90 minutes</option><option value='90..120'>90 to 120 minutes</option><option value='>120'>More than 120 minutes</option>".html_safe %>
#   <%= submit_tag("Search") %>
# <% end %>

  def search

    @results = Movie.where("title like ?", "%#{params[:title]}%")

  end

  protected

  def movie_params
    params.require(:movie).permit(
      :title, :release_date, :director, :runtime_in_minutes, :url, :poster_image, :description
    )
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :restrict_access
  before_filter :load_movie

  def new
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully"
    else
      render :new
    end
  end

  protected

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      if admin?
        redirect_to session_chooseadmin_path, notice: "Hi, #{@user.firstname}."
      else
        redirect_to movies_path, notice: "Welcome back, #{@user.firstname}!"
      end
    else
      flash.now[:alert] = "Log in failed. Balls."
      render :new
    end
  end

  def chooseadmin

  end

  def setadmin
    if params[:yes] || session[:admin] == true
      session[:admin] = true
      redirect_to movies_path, notice: "Logged in as Admin."
    else
      redirect_to movies_path, notice: "Logged in as User."
    end
  end

  def destroy
    session[:user_id] = nil
    session[:admin] = nil
    redirect_to movies_path, notice: "Thanks for stopping by."
  end

  def admin?
    @user.admin
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    admin = params[:admin]
    @user = User.new(user_params)
    
    if admin == "true"
      @user.update(admin: true)
    end

    if @user.save
      if session[:admin]
        redirect_to movies_path, notice: "User #{@user.firstname} #{@user.lastname} successfully created."
      else
        session[:user_id] = @user.id
        redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}."
      end
    else
      render :new
    end
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation, :admin)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end
  
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/new.html.erb
<h1>Log in as admin?</h1>
<%= form_tag do %>
  <div>
  <%= check_box_tag(:yes) %>
  <%= label_tag(:yes, "Yes") %>
  <%= check_box_tag(:no) %>
  <%= label_tag(:no, "No") %>
  </div>
  <div>
    <input type="submit" value="Submit">
  </div>
<% end %>

app/views/admin/users/show.html.erb
<%= paginate @users %>

<%= link_to "Create new user", new_user_path %>

<table>
  <tr>
    <th>Name</th>
    <th>E-mail</th> 
    <th>Admin?</th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.full_name %></td>
      <td><%= user.email %></td>
      <td><% if user.admin %></td>
        <td>Yes</td>
        <% else %>
        <td>No</td>
        <% end %>
      <td>(<%= link_to "delete", admin_users_path(id:user.id), method: :delete, data: { confirm: "Are you sure?" } %>)</td>
    </tr>
  <% end %>
</table>

app/views/layouts/_footer.html.erb
<footer>
  <div class="footer-links">
    <small>
      <% if current_user %>
        Signed in as 
          <% if session[:admin] %>
            <%= link_to "Admin", admin_users_path  %>
          <% else %>
            <%= current_user.full_name %>
          <% end %>
            (<%= link_to "Log out", session_path("current"), method: :delete %>)
      <% else %>
        <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
      <% end %>
    </small>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rotten Mangos</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'app/assets/stylesheets/css/skeleton.css' %>
  <%= stylesheet_link_tag 'app/assets/stylesheets/css/normalize.css' %>
  <%= stylesheet_link_tag 'app/assets/stylesheets/css/custom.css' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value) %>
  <% end %>

  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, :html => { :multipart => true } do |f| %>
  <% if @movie.errors.any? %>
    <div>
      <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div>
  <div>
    <div>
      <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>
    </div>
    <div>
      <%= f.label :release_date %>
      <%= f.date_field :release_date %>
    </div>
    <div>
      <%= f.label :director%>
      <%= f.text_field :director%>
    </div>
    <div>
      <%= f.label :runtime_in_minutes %>
      <%= f.number_field :runtime_in_minutes %>
    </div>
    <div>
      <%= f.file_field :poster_image %>
    </div>
    <div>
      <%= f.label :url %>
      <%= f.text_field :url %>
    </div>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.submit "Ship it!" %>
  </div>
</div>
<% end %>

app/views/movies/_movie.html.erb
<div class="poster">
  <%= link_to movie_path(movie)  do %>
    <%= image_tag(movie.poster_image_url(:thumb) ? movie.poster_image_url(:thumb) : movie.url) %>
  <% end %>
</div>

<div class="text-content">
  <h2><%= link_to movie.title, movie_path(movie) %></h2>
  <h3><%= formatted_date(movie.release_date) %></h3>
  <h4>Dir. <%= movie.director %> | <%= movie.runtime_in_minutes %> minutes</h4>
  <p><%= movie.review_average %>/10</p>
  <p> <%= movie.description %></p>
  <hr>
</div>
  

app/views/movies/_movies.html.erb
  <%= link_to image_tag(movie.poster_image_url(:thumb) ? movie.poster_image_url(:thumb) : movie.url), movie_path(movie) %>
  <h2><%= link_to movie.title, movie_path(movie) %></h2>
  <h3><%= formatted_date(movie.release_date) %></h3>
  <h4>Dir. <%= movie.director %> | <%= movie.runtime_in_minutes %> minutes</h4>
  <p><%= movie.review_average %>/10</p>
  <p> <%= movie.description %></p>
  <hr>

app/views/movies/edit.html.erb
<%= link_to "Back to movie", movie_path(@movie) %>

<h2>Edit this movie.</h2>
<%= render 'form' %>

app/views/movies/index.html.erb
<div class="container">
  <h1>rotten mangos</h1>
  <%= link_to "Submit a movie!", new_movie_path %>
</div>

<hr>

<div class="container search-block">
  <%= form_tag movies_path, :method => 'get' do %>
    <div>
      <div class="form-field">
        <%= label_tag(:title, "Title:") %>
        <%= text_field_tag(:title) %>
      </div>
      <div class="form-field">
        <%= label_tag(:director, "Director:") %>
        <%= text_field_tag(:director) %>
      </div>
      <div class="form-field">
        <%= label_tag(:runtime_in_minutes, "Duration:") %>
        <%= select_tag :runtime_in_minutes, "<option value></option><option value='<90'>Less than 90 minutes</option><option value='90..120'>90 to 120 minutes</option><option value='>120'>More than 120 minutes</option>".html_safe %>
      </div>
      <div class="form-field">
        <%= submit_tag("Search") %>
      </div>
    </div>
  <% end %>
</div>


<div class="container show-movie">
<% @movies.each do |movie| %>
  <div class="movie-index">
    <%= render partial: 'movie', object: movie %>
  </div>
<% end %>
</div>

app/views/movies/new.html.erb
<div class="container">
<%= link_to "Back to all movies", movies_path %>
</div>
<div class="container submit-page">
  <div>
    <h2>Submit a movie!</h2>
    <div class="container submit-form">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/movies/search.html.erb
<h1>Search Results:</h1>

<div>
<% @results.each do |movie| %>
  <h2><%= movie.title %></h2>
  <h3>Directed by <%= movie.director %></h3>
  <h4>Runtime: <%= movie.runtime_in_minutes %> min.</h4>
<% end %>
</div>

app/views/movies/show.html.erb
  <%= link_to "Back to all movies", movies_path %><br/>
<div class="container show-movie">

  <div class="poster">
    <%= link_to image_tag(@movie.poster_image_url(:thumb) ? @movie.poster_image_url(:thumb) : @movie.url), movie_path(@movie) %>
  </div>

  <div class="text-content">
    <h2><%= @movie.title %> (<%= link_to "edit", edit_movie_path(@movie) %>, <%= link_to "delete", movie_path(@movie), method: :delete, data: { confirm: "Are you sure?" } %>)</h2>
    <h3><%= formatted_date(@movie.release_date) %></h3>
    <h4>Dir. <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes</h4>
    <p> <%= @movie.description %></p>

    <hr>

    <h3>Reviews of <em><%= @movie.title %></em></h3>
    <% if current_user %>
        <p>Average rating: <%= @movie.review_average %>/10</p>
      <% @movie.reviews.each do |review| %>
        <p><%= review.text %> <strong><%= review.rating_out_of_ten%>/10</strong></p>
        <small>- <%= review.user.full_name %></small><br/>
      <% end %>
      <p><%= link_to "Write a review!", new_movie_review_path(@movie)%></p>
    <% else %>
      <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p>
    <% end %>
  </div>
</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<%= link_to "Back to movie", movie_path(@movie) %>

<h2>Write a reivew of <em><%= @movie.title %></em>.</h2>

<%= form_for([@movie, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div>
      <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :text %><br>
    <%= f.text_area "text" %>
  </div>
  <div>
    <%= f.label :rating_out_of_ten %><br>
    <%= f.number_field :rating_out_of_ten %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<% if session[:admin] %>
  <h1>Create User</h1>
<% else %>
  <h1>Sign Up</h1>
<% end %>
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div>
        <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :firstname, "First Name" %><br>
    <%= f.text_field :firstname %>
  </div>
  <div>
    <%= f.label :lastname, "Last Name" %><br>
    <%= f.text_field :lastname %>
  </div>
  <% if session[:admin] %>
    <div>
      <%= check_box_tag(:admin, true) %>
      <%= label_tag(:yes, "Make Admin?") %>
    </div>
  <% end %>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.submit "Submit" %>
  </div>
<% end %>